language: php

services:
  - redis-server

php:
- 5.6
- 7.0
- 7.1
- 7.2
- hhvm
-
before_install: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
- composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
  - php: 5.6
  - php: hhvm
  fast_finish: true